### PR TITLE
small documentation fix

### PR DESCRIPTION
**Pull request by laenglea**
Hi,
I found a small bug in the docker-compose syntax and fixed it.

I also have some small suggestions in the readme.md. 

Maybe you like them.

### CODE REVIEW

**Comment by saimonsez** [comment]
You are using an old version of docker compose and these changes refer to a deprecated syntax. This PR should be rejected.

**Comment by laenglea** [comment]
> You are using an old version of docker compose and these changes refer to a deprecated syntax. This PR should be rejected.

You are right. wasn't aware that you don't need the - anymore

**Comment by wimaha** [comment]
Hi @laenglea,

thank you for your effort! ☺️
But @saimonsez is right. You can read about it [here](https://docs.docker.com/compose/migrate/).

**Comment by laenglea** [comment]
Hi @wimaha,

If there is a new way I would prefer it too.

I just tried to use docker compose without the slash on the raspberry with docker installed the way you suggested and it seems in their package the compose v2 is still not there.

So maybe it depends on who the documentation is for.

**Pull request closed without merging**
